objc: true
clean: true
author: BuyBuddy
author_url: http://dev.buybuddy.co
github_url: https://github.com/heybuybuddy/BuyBuddy.app
github_file_prefix: https://github.com/heybuybuddy/BuyBuddy.app/tree/2.0.0
module_version: 2.0.0
module: BuyBuddyKit
theme: fullwidth
output: Documentation/_build
umbrella_header: Source/BuyBuddyKit.h
