language: objective-c  
osx_image: xcode9.2
xcode_project: BuyBuddyKit.xcodeproj 

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
  
matrix:
  include:
    - osx_image: xcode9.2
      env: FASTLANE_LANE=code_coverage FASTLANE_ENV=default
    - osx_image: xcode9.2
      env: FASTLANE_ENV=ios11_xcode9
    - osx_image: xcode9.2
      env: FASTLANE_ENV=tvos11_xcode9
    - osx_image: xcode9.2
      env: FASTLANE_ENV=osx
    - osx_image: xcode8.3
      env: FASTLANE_ENV=ios10_xcode8
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios9_xcode7
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios8_xcode7

